dist: bionic
language: python
python:
  - "3.7"
  - "3.8-dev"

before_install:
  - python --version
  - pip --version

install:
  - pip install --upgrade pip
  - pip install poetry
  - poetry install

script:
  - make lint
  - make test
